server:
  port: 80

spring:
 datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
 redis:
   host: localhost
   port: 6379
   password: 123456
   database: 0
 cache:
   redis:
     time-to-live: 1800000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: D:\BaiduNetdiskDownload\img\
email:
  emailUserName: 1453917871@qq.com
  emailPassWord: gwpcoihxqclvbaae